name: arius
description: Open Source Inventory Management System
homepage: https://arius.org
notifications: false
buildpack: https://github.com/mjmair/heroku-buildpack-python#v216-mjmair
env:
  - STACK=heroku-20
  - DISABLE_COLLECTSTATIC=1
  - ARIUS_DB_ENGINE=sqlite3
  - ARIUS_DB_NAME=database.sqlite3
  - ARIUS_PLUGINS_ENABLED
  - ARIUS_MEDIA_ROOT=/opt/arius/media
  - ARIUS_STATIC_ROOT=/opt/arius/static
  - ARIUS_BACKUP_DIR=/opt/arius/backup
  - ARIUS_PLUGIN_FILE=/opt/arius/plugins.txt
  - ARIUS_CONFIG_FILE=/opt/arius/config.yaml
after_install: contrib/packager.io/postinstall.sh
before:
  - contrib/packager.io/before.sh
dependencies:
  - curl
  - python3
  - python3-venv
  - python3-pip
  - python3-cffi
  - python3-brotli
  - python3-wheel
  - libpango-1.0-0
  - libharfbuzz0b
  - libpangoft2-1.0-0
  - gettext
  - nginx
  - jq
  - libffi7
targets:
  ubuntu-20.04: true
  debian-11: true
